simulator.setDateTime({hour=20, min=0, sec=0, lock=true})

simulator.loadModel("../models/fwexample.bin")
simulator.pressKey(KEY_ENTER) -- Ack the checklist warnings
simulator.pressKey(KEY_SYS) -- System page

simulator.turnRotaryEncoder(1) -- File manager selected
simulator.screenshot("../assets/system-icon-filemanager.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/system-filemanager-sd.png")
simulator.pressKey(KEY_PAGE)
simulator.screenshot("../assets/system-filemanager-flash.png")
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-icon-alerts.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/system-alerts.png")
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-icon-date.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/system-date.png")
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-icon-general.png")
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-general.png")
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER, 0.6)
simulator.screenshot("../assets/system-general-brightness-menu.png")
simulator.turnRotaryEncoder(3)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(5)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(2)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(8)
simulator.pressKey(KEY_ENTER)
simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)
simulator.screenshot("../assets/system-general-brightness-slider.png")
simulator.turnRotaryEncoder(1)
simulator.pressKey(KEY_ENTER)
simulator.turnRotaryEncoder(4)
simulator.screenshot("../assets/system-general-sleep.png")
simulator.pressKey(KEY_RTN)
simulator.turnRotaryEncoder(2)
simulator.screenshot("../assets/system-general-sleep-brightness.png")

simulator.pressKey(KEY_RTN)
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-icon-battery.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/system-battery.png")
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-icon-hardware.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/system-hardware.png")
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-icon-sticks.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/system-sticks.png")
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-icon-devices.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/system-devices.png")
simulator.pressKey(KEY_RTN)

simulator.turnRotaryEncoder(1)
simulator.screenshot("../assets/system-icon-info.png")
simulator.pressKey(KEY_ENTER)
simulator.screenshot("../assets/system-info.png")
simulator.pressKey(KEY_RTN)
